; =======================================================
; QUARTIER GENERALE PLATFORMIO - MULTI-BOARD
; =======================================================

; 1. AMBIENTE PER LA TUA ESP32-S3 (N16R8)
[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi 

lib_ldf_mode = deep+
build_src_filter = +<*> -<tests/>

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1 
lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    mlesniew/PicoMQTT @ ^0.3.8
    adafruit/Adafruit NeoPixel @ ^1.11.0
    adafruit/Adafruit SGP30 Sensor @ ^2.0.3
    Wire
    WiFi
; -------------------------------------------------------

; 2. AMBIENTE PER LA ESP32 NORMALE (Classica)
[env:esp32_classica]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; --- AGGIUNGI QUESTE RIGHE DA QUI ---
; 1. Forza la scansione profonda per trovare Wire.h e WiFi.h ovunque
lib_ldf_mode = deep+

; 2. Evita che PlatformIO provi a compilare la cartella dei test durante una build normale
build_src_filter = +<*> -<tests/>
; ------------------------------------

lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    Wire
    WiFi