[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; ----------------------------------------------------
; CONFIGURAZIONE SPECIFICA PER N16R8
; ----------------------------------------------------
; Dichiara i 16MB di Flash
board_upload.flash_size = 16MB
; Usa una tabella delle partizioni che sfrutti tutti i 16MB
board_build.partitions = default_16MB.csv
; FONDAMENTALE: Le versioni R8 usano memoria Octal SPI (OPI)
board_build.arduino.memory_type = qio_opi 

; ----------------------------------------------------
; FLAG DI COMPILAZIONE (PSRAM e USB)
; ----------------------------------------------------
build_flags = 
    ; Abilita l'uso degli 8MB di PSRAM
    -DBOARD_HAS_PSRAM
    ; Abilita la stampa seriale sulla porta USB nativa (cruciale per le S3)
    -DARDUINO_USB_CDC_ON_BOOT=1 

; ----------------------------------------------------
; LIBRERIE
; ----------------------------------------------------
lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8